language: python

python:
    - 3.9

before_install:
  - pip install poetry

install:
  - poetry install
  
script:
    - flake8
    - python3 -m venv .venv
    - source./venv/bin/activate
    - pip install -r requirements-dev.txt
